import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Main from "@/components/Main";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <TooltipProvider>
            {/* <UserProvider initialUser={userJson.user}> */}
            {/* <CategoriesProvider initialCategories={categories}> */}
            <AppSidebar />
            <Main>
              <SidebarTrigger />
              {children}
            </Main>
            {/* </CategoriesProvider> */}
            {/* </UserProvider> */}
          </TooltipProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
