create type "public"."message_type" as enum ('text', 'image', 'emoji');

drop trigger if exists "handle_messages_insert" on "public"."messages";


  create table "public"."message_reactions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message_id" bigint not null,
    "user_id" bigint not null,
    "reaction" text not null
      );


alter table "public"."message_reactions" enable row level security;

alter table "public"."messages" add column "deleted" boolean not null default false;

alter table "public"."messages" add column "image_path" text;

alter table "public"."messages" add column "type" public.message_type;

alter table "public"."messages" add column "updated_at" timestamp with time zone;

alter table "public"."room_user" add column "last_read_message_id" bigint;

CREATE UNIQUE INDEX message_reactions_pkey ON public.message_reactions USING btree (id);

alter table "public"."message_reactions" add constraint "message_reactions_pkey" PRIMARY KEY using index "message_reactions_pkey";

alter table "public"."message_reactions" add constraint "message_reactions_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE not valid;

alter table "public"."message_reactions" validate constraint "message_reactions_message_id_fkey";

alter table "public"."message_reactions" add constraint "message_reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."message_reactions" validate constraint "message_reactions_user_id_fkey";

alter table "public"."room_user" add constraint "room_user_last_read_message_id_fkey" FOREIGN KEY (last_read_message_id) REFERENCES public.messages(id) ON DELETE SET NULL not valid;

alter table "public"."room_user" validate constraint "room_user_last_read_message_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.message_reactions_broadcast()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  target_room_id bigint;
begin
  if TG_OP = 'INSERT' then
    select m.room_id
      into target_room_id
    from public.messages m
    where m.id = NEW.message_id;

    if target_room_id is null then
      return null;
    end if;

    perform realtime.broadcast_changes(
      'channel:' || target_room_id::text || ':reactions',
      'INSERT',
      'INSERT',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      NEW,
      null
    );

  elsif TG_OP = 'UPDATE' then
    select m.room_id
      into target_room_id
    from public.messages m
    where m.id = NEW.message_id;

    if target_room_id is null then
      return null;
    end if;

    perform realtime.broadcast_changes(
      'channel:' || target_room_id::text || ':reactions',
      'UPDATE',
      'UPDATE',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      NEW,
      OLD
    );

  elsif TG_OP = 'DELETE' then
    select m.room_id
      into target_room_id
    from public.messages m
    where m.id = OLD.message_id;

    if target_room_id is null then
      return null;
    end if;

    perform realtime.broadcast_changes(
      'channel:' || target_room_id::text || ':reactions',
      'DELETE',
      'DELETE',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      null,
      OLD
    );
  end if;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.room_user_read_broadcast()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if NEW.last_read_message_id is distinct from OLD.last_read_message_id then
    perform realtime.broadcast_changes(
      'channel:' || NEW.room_id::text || ':read_status',
      'READ_UPDATE',
      'UPDATE',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      NEW,
      OLD
    );
  end if;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.messages_broadcast()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  room_topic text;
begin
  if TG_OP = 'INSERT' then
    room_topic := 'channel:' || NEW.room_id::text;

    perform realtime.broadcast_changes(
      room_topic,
      'INSERT',
      'INSERT',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      NEW,
      null
    );

  elsif TG_OP = 'UPDATE' then
    room_topic := 'channel:' || NEW.room_id::text;

    perform realtime.broadcast_changes(
      room_topic,
      'UPDATE',
      'UPDATE',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      NEW,
      OLD
    );

  elsif TG_OP = 'DELETE' then
    room_topic := 'channel:' || OLD.room_id::text;

    perform realtime.broadcast_changes(
      room_topic,
      'DELETE',
      'DELETE',
      TG_TABLE_NAME,
      TG_TABLE_SCHEMA,
      null,
      OLD
    );
  end if;

  return null;
end;
$function$
;

grant delete on table "public"."message_reactions" to "anon";

grant insert on table "public"."message_reactions" to "anon";

grant references on table "public"."message_reactions" to "anon";

grant select on table "public"."message_reactions" to "anon";

grant trigger on table "public"."message_reactions" to "anon";

grant truncate on table "public"."message_reactions" to "anon";

grant update on table "public"."message_reactions" to "anon";

grant delete on table "public"."message_reactions" to "authenticated";

grant insert on table "public"."message_reactions" to "authenticated";

grant references on table "public"."message_reactions" to "authenticated";

grant select on table "public"."message_reactions" to "authenticated";

grant trigger on table "public"."message_reactions" to "authenticated";

grant truncate on table "public"."message_reactions" to "authenticated";

grant update on table "public"."message_reactions" to "authenticated";

grant delete on table "public"."message_reactions" to "postgres";

grant insert on table "public"."message_reactions" to "postgres";

grant references on table "public"."message_reactions" to "postgres";

grant select on table "public"."message_reactions" to "postgres";

grant trigger on table "public"."message_reactions" to "postgres";

grant truncate on table "public"."message_reactions" to "postgres";

grant update on table "public"."message_reactions" to "postgres";

grant delete on table "public"."message_reactions" to "service_role";

grant insert on table "public"."message_reactions" to "service_role";

grant references on table "public"."message_reactions" to "service_role";

grant select on table "public"."message_reactions" to "service_role";

grant trigger on table "public"."message_reactions" to "service_role";

grant truncate on table "public"."message_reactions" to "service_role";

grant update on table "public"."message_reactions" to "service_role";


  create policy "all"
  on "public"."message_reactions"
  as permissive
  for all
  to public
using (true)
with check (true);


CREATE TRIGGER handle_message_reactions_change AFTER INSERT OR DELETE OR UPDATE ON public.message_reactions FOR EACH ROW EXECUTE FUNCTION public.message_reactions_broadcast();

CREATE TRIGGER handle_messages_change AFTER INSERT OR DELETE OR UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.messages_broadcast();

CREATE TRIGGER handle_room_user_read_update AFTER UPDATE ON public.room_user FOR EACH ROW EXECUTE FUNCTION public.room_user_read_broadcast();


  create policy "all 1rdzryk_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'messages'::text));



  create policy "all 1rdzryk_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'messages'::text));



  create policy "all 1rdzryk_2"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'messages'::text));



  create policy "all 1rdzryk_3"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'messages'::text));



