create type "public"."notification_type" as enum ('message', 'friend_request');


  create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" public.notification_type not null,
    "recipient_user_id" bigint not null,
    "actor_user_id" bigint not null,
    "message_id" bigint,
    "friend_request_id" bigint,
    "room_id" bigint,
    "read_at" timestamp with time zone,
    "actor_image_path" text,
    "message_preview" text,
    "message_type" public.message_type,
    "actor_display_name" text
      );


alter table "public"."notifications" enable row level security;

CREATE UNIQUE INDEX notifications_friend_request_id_key ON public.notifications USING btree (friend_request_id);

CREATE UNIQUE INDEX notifications_message_id_key ON public.notifications USING btree (message_id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."notifications" add constraint "notifications_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_actor_user_id_fkey";

alter table "public"."notifications" add constraint "notifications_friend_request_id_fkey" FOREIGN KEY (friend_request_id) REFERENCES public.friend_requests(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_friend_request_id_fkey";

alter table "public"."notifications" add constraint "notifications_friend_request_id_key" UNIQUE using index "notifications_friend_request_id_key";

alter table "public"."notifications" add constraint "notifications_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_message_id_fkey";

alter table "public"."notifications" add constraint "notifications_message_id_key" UNIQUE using index "notifications_message_id_key";

alter table "public"."notifications" add constraint "notifications_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_recipient_user_id_fkey";

alter table "public"."notifications" add constraint "notifications_room_id_fkey" FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_room_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_friend_request_notifications()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor_display_name text;
  v_actor_image_path text;
begin
  if new.status <> 'pending' then
    return null;
  end if;

  select
    p.display_name,
    p.image_path
  into
    v_actor_display_name,
    v_actor_image_path
  from public.profiles p
  where p.id = new.sender_id;

  insert into public.notifications (
    type,
    recipient_user_id,
    actor_user_id,
    friend_request_id,
    actor_display_name,
    actor_image_path,
    message_preview
  )
  values (
    'friend_request'::public.notification_type,
    new.receiver_id,
    new.sender_id,
    new.id,
    coalesce(v_actor_display_name, 'Unknown user'),
    v_actor_image_path,
    'sent you a friend request'
  );

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_message_notifications()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor_display_name text;
  v_actor_image_path text;
  v_message_preview text;
begin
  select
    p.display_name,
    p.image_path
  into
    v_actor_display_name,
    v_actor_image_path
  from public.profiles p
  where p.id = new.user_id;

  v_message_preview :=
    case
      when new.type = 'text' then left(coalesce(new.body, ''), 80)
      when new.type = 'image' then 'Sent an image'
      when new.type = 'emoji' then left(coalesce(new.body, ''), 80)
      else null
    end;

  insert into public.notifications (
    type,
    recipient_user_id,
    actor_user_id,
    message_id,
    room_id,
    actor_display_name,
    actor_image_path,
    message_preview,
    message_type
  )
  select
    'message'::public.notification_type,
    ru.user_id,
    new.user_id,
    new.id,
    new.room_id,
    coalesce(v_actor_display_name, 'Unknown user'),
    v_actor_image_path,
    v_message_preview,
    new.type
  from public.room_user ru
  where ru.room_id = new.room_id
    and ru.user_id <> new.user_id;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.mark_message_notifications_as_read()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if new.last_read_message_id is null then
    return null;
  end if;

  if new.last_read_message_id is not distinct from old.last_read_message_id then
    return null;
  end if;

  update public.notifications
  set read_at = now()
  where type = 'message'::public.notification_type
    and recipient_user_id = new.user_id
    and room_id = new.room_id
    and read_at is null
    and message_id is not null
    and message_id <= new.last_read_message_id;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.notifications_broadcast()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  notification_topic text;
begin
  if tg_op = 'INSERT' then
    notification_topic := 'notification:' || new.recipient_user_id::text;

    perform realtime.broadcast_changes(
      notification_topic,
      'INSERT',
      'INSERT',
      tg_table_name,
      tg_table_schema,
      new,
      null
    );

  elsif tg_op = 'UPDATE' then
    notification_topic := 'notification:' || new.recipient_user_id::text;

    perform realtime.broadcast_changes(
      notification_topic,
      'UPDATE',
      'UPDATE',
      tg_table_name,
      tg_table_schema,
      new,
      old
    );
  end if;

  return null;
end;
$function$
;

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "postgres";

grant insert on table "public"."notifications" to "postgres";

grant references on table "public"."notifications" to "postgres";

grant select on table "public"."notifications" to "postgres";

grant trigger on table "public"."notifications" to "postgres";

grant truncate on table "public"."notifications" to "postgres";

grant update on table "public"."notifications" to "postgres";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";


  create policy "all"
  on "public"."notifications"
  as permissive
  for all
  to public
using (true)
with check (true);


CREATE TRIGGER handle_friend_request_notifications AFTER INSERT ON public.friend_requests FOR EACH ROW EXECUTE FUNCTION public.create_friend_request_notifications();

CREATE TRIGGER handle_message_notifications AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.create_message_notifications();

CREATE TRIGGER handle_notifications_broadcast AFTER INSERT OR UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION public.notifications_broadcast();

CREATE TRIGGER handle_room_user_message_notifications_read AFTER UPDATE ON public.room_user FOR EACH ROW EXECUTE FUNCTION public.mark_message_notifications_as_read();


  create policy "users can receive own notification broadcasts"
  on "realtime"."messages"
  as permissive
  for select
  to authenticated
using (((extension = 'broadcast'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles p
  WHERE ((p.user_id = auth.uid()) AND (('notification:'::text || (p.id)::text) = realtime.topic()))))));



